name: My First Workflow

on:
  workflow_dispatch:
  push:
    paths:
      - "02-first-workflow/**"
      - ".github/workflows/hello.yml"

jobs:
  hello:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18, 20]
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: 버전 출력
        run: |
          echo "이번 복제본의 Node 버전 후보: ${{ matrix.node }}"

  done:
    runs-on: ubuntu-latest
    needs: hello
    steps:
      - name: 완료 알림
        run: |
          echo "hello 3개(16/18/20)가 다 끝나서 done 실행됨"
